version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=pma
      - MARIADB_DATABASE=app
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/bitnami/mariadb
    networks:
      - test
  myapp:
    image: docker.io/bitnami/laravel:8
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=pma
      - DB_DATABASE=app
    volumes:
      - './todo/:/app'
    depends_on:
      - mariadb
    networks:
      - test

  phpmyadmin:
      image: phpmyadmin/phpmyadmin

      links: 
          - mariadb
      ports:
          - 9000:80
      environment:
          PMA_HOST: mariadb
          
      networks:
          - test
        
volumes:
    persistent:

networks:
  test:
    driver: bridge
